# Generated by Django 4.2.3 on 2023-08-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_producto_descuento_alter_producto_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen o Video'),
        ),
    ]
