# Generated by Django 4.2.3 on 2023-08-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_categoria_cantidad_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='categ/', verbose_name='Imagen o Video'),
        ),
    ]
