# Generated by Django 4.2.3 on 2023-08-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_categoria_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='cantidad_productos',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='categoria/', verbose_name='Imagen o Video'),
        ),
    ]
