# Generated by Django 4.2.3 on 2023-08-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_categoria_cantidad_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='cantidad_productos',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
