# Generated by Django 4.2.3 on 2023-08-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_categoria_cantidad_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='cantidad_productos',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
